//List of keywords to be parsed

TOKEN(And, "and")
TOKEN(Break, "break")
TOKEN(Do, "do")
TOKEN(Else, "else")
TOKEN(Elseif, "elseif")
TOKEN(End, "end")
TOKEN(False, "false")
TOKEN(For, "for")
TOKEN(Function, "function")
TOKEN(If, "if")
TOKEN(In, "in")
TOKEN(Local, "local")
TOKEN(Nil, "nil")
TOKEN(Not, "not")
TOKEN(Or, "or")
TOKEN(Repeat, "repeat")
TOKEN(Return, "return")
TOKEN(Then, "then")
TOKEN(True, "true")
TOKEN(Until, "until")
TOKEN(While, "while")